### ISSUE TITLE
Iteration of the Dyson-Schwinger equations

### ISSUE THREAD

**Issue by ftcbrandt** [markusqh/DoFun#1]
Are there plans to implement an iteration procedure, so that one could obtain all the Feynman diagrams which contribute to a given order?

**Comment by markusqh** [comment]
Currently not, but the recursion to get that should be possible with what is available now. However, I would not expect it to be very efficient for high orders due to the large number of terms generated and how they are handled in Mathematica. Suggestions for the realization are welcome.
