### ISSUE TITLE
Problems with graph generation.

### ISSUE THREAD

**Issue by Felipe-4** [markusqh/DoFun#2]
<img width="1440" alt="Captura de Tela 2024-02-15 às 13 19 58" src="https://github.com/markusqh/DoFun/assets/110336310/ffcd5da4-abc9-426b-858a-32b1129ccf17">
I am on mathematica 13.3.1,  and when I tried to generate the diagrams I get the error 

"An unknown box name (DoFun`DoDSERGE`Private`GraphElementData["Line"]) was sent as the BoxForm for the expression. Check the format rules for the expression. "
I installed through the Import method and then I tried again by manually downloading from GitHub, both cases generate this when I try to evaluate.

**Comment by markusqh** [comment]
This was fixed in https://github.com/markusqh/DoFun/commit/4b20897054657621e05593313d64558376d2c87c. Please try the current development version (not the release) as described in the readme.

**Comment by Felipe-4** [comment]
Thank you!
